#!/bin/bash

function yes_or_no {
    while true; do
        echo
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return  0 ;;  
            [Nn]*) return  1 ;;
        esac
    done
}
